server:
  port: 8888

spring:
  application:
    name: config-service
   
  cloud:
    config:
      server:
        git:
#          uri: https://github.com/justdoplzz/msa-config-repo.git   #Github Repository 주소
         uri: https://github.com/Advanc2d/msa-configuration.git   #Docker 확인용 주소
         