server:
  port: 8007

spring:
  application:
    name: error-service-fallback
  profiles:
    active: dev
  config:              # gradle에 config 추가.
    import: optional:configserver:http://localhost:8888  # config 서버 위치
#    import: optional:configserver:http://192.168.1.54:8888  # config 도커로 할때 버전
  devtools:
     livereload:  #﻿ html, css, js 수정 시 새로고침 없이 바로 적용가능
       enabled: true
     restart:   # 재시작시 완전히 꺼졌다 다시키는 것보다 훨씬 빠르게 해줌.
      enabled: true
## 유레카 클라이언트 설정    
#eureka:
#  instance:
#    instance-id:  error-microservice-instance  # eureka에 등록되는 id 값
#  client:
#    register-with-eureka: true  # 유레카에 등록할지 여부.
#    fetch-registry: true  # 유레카에서 조회할지 여부
#    service-url:
#      defaultZone: http://localhost:8761/eureka # 서비스를 등록할 서버 주소를 지정